# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20171004_1442'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='completed',
        ),
        migrations.AddField(
            model_name='post',
            name='body',
            field=models.TextField(default='Body of post goes here'),
        ),
        migrations.AddField(
            model_name='post',
            name='picture',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
